---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: okr-application
  labels:
    app: scrum-poker-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrum-poker-application
  template:
    metadata:
      labels:
        app: scrum-poker-application
    spec:
      containers:
        - name: scrum-poker-application
          image: registry.puzzle.ch/puzzle/okr:1.0.10-PROD
          ports:
            - name: http
              containerPort: 8080
