---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psc-application
  labels:
    app: psc-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psc-application
  template:
    metadata:
      labels:
        app: psc-application
    spec:
      containers:
        - name: psc-application
          image: registry.puzzle.ch/puzzle/scrum-poker:1.0.23-PROD
          ports:
            - name: http
              containerPort: 8080
