name: 'Build'

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Set up node.js version lts/fermium
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - run: npm --prefix frontend/ install

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml -P build-for-docker

      - name: Build the docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.TAG }}:latest