name: 'Build and deploy'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set up node.js version lts/gallium
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/gallium'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        run: npm install --only=prod

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -P build-for-docker

#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag puzzle-scrum-poker:$(date +%s)

    - name: Log in to Quay registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.QUAY_REGISTRY }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: puzzle-scrum-poker:(date +%s)
